var interfaceConfig = {
    APP_NAME: 'Vinay Meet',
    AUDIO_LEVEL_PRIMARY_COLOR: 'rgba(255,255,255,0.4)',
    AUDIO_LEVEL_SECONDARY_COLOR: 'rgba(255,255,255,0.2)',
    AUTO_PIN_LATEST_SCREEN_SHARE: 'remote-only',
    BRAND_WATERMARK_LINK: '',
    CLOSE_PAGE_GUEST_HINT: false,
    DEFAULT_BACKGROUND: '#040404',
    DEFAULT_LOGO_URL: 'images/logo.svg',
    DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/logo.svg',
    DISABLE_DOMINANT_SPEAKER_INDICATOR: false,
    DISABLE_JOIN_LEAVE_NOTIFICATIONS: false,
    DISABLE_PRESENCE_STATUS: false,
    DISABLE_RINGING: false,
    DISABLE_TRANSCRIPTION_SUBTITLES: false,
    DISABLE_VIDEO_BACKGROUND: false,
    DISPLAY_WELCOME_FOOTER: true,
    DISPLAY_WELCOME_PAGE_ADDITIONAL_CARD: false,
    DISPLAY_WELCOME_PAGE_CONTENT: false,
    DISPLAY_WELCOME_PAGE_TOOLBAR_ADDITIONAL_CONTENT: false,
    ENABLE_DIAL_OUT: true,
    ENABLE_FEEDBACK_ANIMATION: false, // Enables feedback star animation.
    FILM_STRIP_MAX_HEIGHT: 120,
    GENERATE_ROOMNAMES_ON_WELCOME_PAGE: true,
    HIDE_DEEP_LINKING_LOGO: false,
    HIDE_INVITE_MORE_HEADER: false,
    JITSI_WATERMARK_LINK: 'https://vinayprasad04.github.io/portfolio',
    LANG_DETECTION: true,
    LIVE_STREAMING_HELP_LINK: 'https://vinayprasad04.github.io/portfolio',
    LOCAL_THUMBNAIL_RATIO: 16 / 9,
    MAXIMUM_ZOOMING_COEFFICIENT: 1.3,
    MOBILE_APP_PROMO: true,
    MOBILE_DOWNLOAD_LINK_ANDROID: 'https://vinayprasad04.github.io/portfolio',
    MOBILE_DOWNLOAD_LINK_F_DROID: 'https://vinayprasad04.github.io/portfolio',
    MOBILE_DOWNLOAD_LINK_IOS: 'https://vinayprasad04.github.io/portfolio',
    NATIVE_APP_NAME: 'Vinay Meet',
    OPTIMAL_BROWSERS: [ 'chrome', 'chromium', 'firefox', 'nwjs', 'electron', 'safari' ],
    POLICY_LOGO: null,
    PROVIDER_NAME: 'Vinay',
    RECENT_LIST_ENABLED: true,
    REMOTE_THUMBNAIL_RATIO: 1,
    SETTINGS_SECTIONS: [ 'devices', 'language', 'moderator', 'profile', 'calendar', 'sounds' ],
    SHOW_BRAND_WATERMARK: false,
    SHOW_CHROME_EXTENSION_BANNER: false,
    SHOW_DEEP_LINKING_IMAGE: false,
    SHOW_JITSI_WATERMARK: true,
    SHOW_POWERED_BY: false,
    SHOW_PROMOTIONAL_CLOSE_PAGE: false,
    SUPPORT_URL: 'https://vinayprasad04.github.io/portfolio',
    UNSUPPORTED_BROWSERS: [],
    VERTICAL_FILMSTRIP: true,
    VIDEO_LAYOUT_FIT: 'both',
    VIDEO_QUALITY_LABEL_DISABLED: false,
    makeJsonParserHappy: 'even if last key had a trailing comma'
};
